### ISSUE TITLE
Hide action for pages

### ISSUE THREAD

**Issue by T3mai** [packstub/filament-account-switcher#2]
https://github.com/xlite-dev/filament-impersonate/blob/cdb3cfb06ae53a42980900cef1c9d0823250775b/src/Pages/Actions/ImpersonateAction.php#L18

Maybe same as for Tables\Actions\ImpersonateAction add method $this->hidden(fn ($record) => ! ImpersonateController::allowed(Filament::auth()->user(), $record));

**Comment by icaliman** [comment]
Thanks for your help @temai23 

If you want, you can make a pull request
